AllCops:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Guardfile'

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'config/application.rb'

Style/LineEndConcatenation:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/IndentHash:
  EnforcedStyle: consistent

Style/BlockComments:
  Enabled: false

Style/BracesAroundHashParameters:
   EnforcedStyle: no_braces

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MethodCallParentheses:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Lint/UselessAssignment:
  Enabled: true
